Repository enafs/devops-aula07, pull requests merged in 2018-03, with the labels that each got.

#2 Integrar requisitos v1.0
  docs/requisitos.md
Labels: análise

#4 issue #3
  docs/arquitetura.md
Labels: arquitetura

#6 V1.0 programacao
  src/jogovelha.py
Labels: programação

#8 V1.0 testes
  src/scripts de teste
  src/testes_inic.py
  src/testes_jogar.py
Labels: testes

#9 V1.0
  docs/arquitetura.md
  docs/requisitos.md
  src/jogovelha.py
  src/scripts de teste
  src/testes_inic.py
  src/testes_jogar.py
Labels: operações
